### ISSUE TITLE
Classification betas not leading to expected results

### ISSUE THREAD

**Issue by nickluger** [openai/openai-node#10]
**What happens:**
Passing `classification_betas`, e.g. `classification_betas: [1, 0.5]` leads to equal f-beta values in the resulting CSV file, although precision and recall differ. The columns are named correctly in the resulting file, e.g. `classification/f0.5` etc, but the cell values always equal `f-1`, not the `β` of the respective column.

**What I expected:**
Differing f-values, as the parameter weighs precision higher (1x, 2x, ... times as much) than recall.

Maybe in interpreted the docs wrongly though, and this parameter is supposed to be used differently.

**Comment by schnerd** [comment]
Thanks for reporting this (and sorry for the delayed response).

This repository is for issues specifically with the openai node.js bindings, rather than the behavior of the API itself. I'll be closing this accordingly, but will pass the feedback onto our team. Feel free to reach out to our support team at https://help.openai.com/en/ if needed.
