### ISSUE TITLE
404 Invalid URL (POST /v1/chat/completions)

### ISSUE THREAD

**Issue by nullRefErr** [openai/openai-node#1074]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Hello all, between 2024-09-15 06:01pm and 2024-09-15 10:00pm we encounter 404 Invalid URL (POST /v1/chat/completions) errors in our logs. Before and after this specific time window all seems fine. I am searching what caused this problem. [There is an incident report on 13th September](https://status.openai.com/incidents/6xrkkj69mwn0). Also I checked that there is no report or annoucement or api down detection on 15th September  If you can explain what is the main reason I would be appreciated. 

### To Reproduce

```
const openaiClient = new OpenAI({
            apiKey: "apikey",
            timeout: 3 * 60 * 1000,
            maxRetries: 2,
 });
 const response = await openaiClient.chat.completions.create({
                model: 'gpt-4o',
                messages: [{ role: 'user', content: 'Hello gpt' }],
});
```

### OS

Ubuntu

### Node version

Node v20.12

### Library version

4.52.2

**Comment by kwhinnery-openai** [comment]
Hi there! Sorry to hear you ran into issues with the API this weekend. 

We didn't have an incident recorded on 9/15, so either we missed something on our end with monitoring, or there could have been something specific to your account and configuration. It will probably require a bit of back-and-forth to get to the bottom of things. Could you use the Intercom chat widget on help.openai.com to start a conversation with our support team? They will be equipped to debug this with you in the context of your account.

I am going to close this issue for now, since this problem is unlikely to involve the actual Node SDK.

Thanks,
-Kevin

**Comment by nullRefErr** [comment]
> help.openai.com

Thanks @kwhinnery-openai 🚀
