### ISSUE TITLE
`zodResponseFormat` should require a zod object, and not any zod type

### ISSUE THREAD

**Issue by uriva** [openai/openai-node#1092]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

it is easy to get it wrong by inputting `z.boolean()` which will later fail in ta cryptic http error
```
400 Invalid schema for response_format 'query': schema must be a JSON Schema of 'type: "object"', got 'type: "None"'.
```

**Comment by RobertCraigie** [comment]
Unfortunately we can't just accept a zod object because of [recursive schemas](https://github.com/openai/openai-node/blob/ee1e4504d74f456800b671d163ad506f73846cca/examples/ui-generation.ts#L19), so I don't think it's feasible to change the type.

I agree this error message is not very helpful though, I've reported this back to the OpenAI API team.
