### ISSUE TITLE
Can't specify max tokens in createChatCompletion

### ISSUE THREAD

**Issue by Blackglade** [openai/openai-node#124]
### Describe the bug

Title pretty much says it all. The api docs specify a max_tokens value:

https://platform.openai.com/docs/api-reference/chat/create

However, when I use the api to create a request:

```
const completion = await openai.createChatCompletion({
	model: "gpt-4",
	messages: [
		{role: 'system', content: prompt},
		...msg
	],
	max_tokens: 300
	top_p: 1,
	frequency_penalty: 1,
	presence_penalty: 0.6,
	temperature: 0.5,
})
```

`max_tokens` doesn't seem to be specified in the input type for the function.

### To Reproduce

1. Get the latest openai-node package (3.2.0)
2. Write out a createChatCompletion request
3. Try to use the `max_tokens` param in the request

### OS

Ventura 13.2

### Node version

Node v18.12.0

### Library version

openai 3.2.0

**Comment by antohasvs** [comment]
Same issue here, `createCompletion` has `max_tokens` option, but `createChatCompletion` doesn't

**Comment by mikib0** [comment]
The problem seems to be from openai directly not the library. When I try this (**max_tokens: 5**):
`curl https://api.openai.com/v1/chat/completions -H "Content-Type: application/json" -H "Authorization: Bearer $OPENAI_API_KEY" -d '{ "model": "gpt-3.5-turbo", "messages": [{"role": "user", "content": "hi"}], "temperature": 0.7, "max_tokens": 12}'`

i get this response (**total_tokens:18**): 
`{"id":"chatcmpl-7A0rtilh4PmLILOdiMBMNIHdkGFjZ","object":"chat.completion","created":1682620973,"model":"gpt-3.5-turbo-0301","usage":{"prompt_tokens":9,"completion_tokens":9,"total_tokens":18},"choices":[{"message":{"role":"assistant","content":"Hello! How can I assist you today?"},"finish_reason":"stop","index":0}]}`

**Comment by adamk22** [comment]
It has the max_tokens property, it wasn't typed properly in 3.2.0, update to 3.2.1 and you should have it
