### ISSUE TITLE
Timeout issue on localhost: connect ETIMEDOUT

### ISSUE THREAD

**Issue by TheAkinator** [openai/openai-node#148]
### Describe the bug

I'm doing a project with NextJS and I'm using this lib to connect with openai ChatGPT API.

Until yesterday I was able to make my requests to:
- `createModeration`
- `createChatCompletion`

But today almost 90% of the time my requests are failing with a timeout erro on localhost (it's working on staging and production):
```
Error: connect ETIMEDOUT 104.18.6.192:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.18.6.192',
  port: 443,
```

I saw some dudes saying that this error usually happens for people that uses VPN or are in China. I'm not using a VPN and I don't live in China too. 

Any idea what could be the cause of it ?

### To Reproduce

Make a call to `createModeration` or `createChatCompletion` on a NextJS server running on localhost

### Code snippets

```JavaScript
const moderationResponse = await openai.createModeration({
  input: message,
});

const completionResponse = await openai.createChatCompletion({
  model: 'gpt-3.5-turbo',
  messages,
  temperature: 0,
  max_tokens: MAX_TOKENS,
  user: userID,
});
```

### OS

macOS

### Node version

Node 16.14.0

### Library version

openai 3.2.1

**Comment by emirpasic** [comment]
Started experiencing a similar issue when firing multiple requests against the `createChatCompletion` endpoint, albeit still under the rate limit of GPT3.5-turbo. For now, we have implemented a retry logic to mitigate the above, but we are also wondering why this is happening.

**Comment by adamk22** [comment]
I have similar experience (more like @emirpasic) but I'm getting a 429 error back even though I'm under the rate limit (see issue: https://github.com/openai/openai-node/issues/165). 

@emirpasic has the retry logic solved it for now?

**Comment by emirpasic** [comment]
@adamk22 i was not getting 429, only a ETIMEDOUT. 429 should be handled with some retry backoff strategy. The ETIMEDOUT we solved by switching to another instance, my suspicion is that OpenAI banned that IP address due to large number of requests (although within the limits). If we encounter the problem again, we'll have to pass the requests through proxies.

**Comment by rattrayalex** [comment]
It doesn't sound like this is an SDK bug, so I'm closing this issue.

**Comment by rattrayalex** [comment]
You may encounter `ETIMEDOUT` if there is a problem connecting from your computer to OpenAI's servers, perhaps because it is blocked somewhere along the chain, or due to networking issues. 

If you encounter this issue when using the SDK but not when making the request directly, please open a new issue on this repo.
