### ISSUE TITLE
Error: Request failed with status code 400

### ISSUE THREAD

**Issue by JoeABCDEF** [openai/openai-node#154]
### Describe the bug

![image](https://user-images.githubusercontent.com/39638510/234624946-d7f3ebb7-1371-4224-8daa-7539b28fa62d.png)
![image](https://user-images.githubusercontent.com/39638510/234619589-87dfa779-c9d4-4d0e-8779-eb2e6a607e7f.png)
![image](https://user-images.githubusercontent.com/39638510/234621089-d602bf15-eb62-457a-8175-c5c34bc3d201.png)

Too much content will cause an error, It's not clear to me why that's true

### To Reproduce

1. Too much content

### OS

windows

### Node version

Node V18.x

### Library version

openai v3.2.1

**Comment by HYliangkai** [comment]
感觉是流式传输的问题...我也老遇到这些bug..

**Comment by JoeABCDEF** [comment]
> 感觉是流式传输的问题...我也老遇到这些bug..

@HYliangkai 你改回正常的就行了吗?

**Comment by khaninejad** [comment]
I have this problem as well. 
If you use `text-davinci-003 `most likely you won't face this issue but I have this issue with other models and only` text-davinci-003` works for me.

**Comment by Rishabh-Gaud** [comment]
@khaninejad still facing the same problem with using `text-davinci-003`

**Comment by khaninejad** [comment]
Okay, here's what I found:

Firstly, I was using a non-compatible model for completions. In the main documentation, it is stated that you can use any model, but you can check if a model is suitable for your needs using the following link: 
https://platform.openai.com/docs/models/model-endpoint-compatibility

The second issue I encountered was related to error handling. I highly recommend wrapping the async function in a try-catch block to catch errors. Here's an example:

```
try {
  // your async function here
} catch (error) {
  if (error.response) {
    console.log(error.response.status);
    console.log(error.response.data);
  } else {
    console.log(error.message);
  }
}
```

Lastly, if you're not sure whether the problem is related to the library or not, you can use Postman to send the prompt directly to OpenAI for testing.

**Comment by rattrayalex** [comment]
Our new [v4](https://github.com/openai/openai-node/discussions/182) should include more helpful error messages. Please open a new issue if you run into continued problems with it.
