### ISSUE TITLE
[Whisper] verbose_json responseFormat should return correct type

### ISSUE THREAD

**Issue by MrRefactoring** [openai/openai-node#155]
### Describe the bug

When I use **responseType** **verbose_json**, I get a typescript error. The request returns segments, which is not present in the response types

### To Reproduce

```ts
const { data: { segments } } = await this.openAiClient.createTranslation( // TypeScript throws an error here
  readStream as unknown as File, // voice file
  'whisper-1', // model
  undefined, // prompt
  'verbose_json', // reponseType. This means another response type should used
  0.2, // temperature
);
```

### OS

macOs

### Node version

Node v18.14.0

### Library version

openai v3.2.1

**Comment by rattrayalex** [comment]
The code provided does not seem to be this SDK; the bug may be present in another library you're using. 

Our upcoming v4 of this library has support for this format, though it currently isn't typed: https://github.com/openai/openai-node/blob/v4/src/resources/audio/transcriptions.ts#L54 

This should be fixed by https://github.com/openai/openai-openapi/pull/58
