### ISSUE TITLE
Support for use in front end environment instead of node

### ISSUE THREAD

**Issue by sunset1234321** [openai/openai-node#295]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

Could we use this in  JavaScript  such as  React?

**Comment by rattrayalex** [comment]
This is discouraged because you could expose your API keys to attackers: https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety

The safest way to use this library in the client is to set a custom `baseURL` to proxy through your own backend service, and add the API key there instead of in the client. For use-cases like this, or gated to a trusted network, you can pass `dangerouslyAllowBrowser: true` to enable client-side use of the library.
