### ISSUE TITLE
wrong implementation of uuid algorithm

### ISSUE THREAD

**Issue by OleksandrKucherenko** [openai/openai-node#303]
### Confirm this is a Node library issue and not an underlying OpenAI API issue

- [X] This is an issue with the Node library

### Describe the bug

Note: The use of any UUID generator that relies on Math.random() is strongly discouraged (including snippets featured in previous versions of this answer) for reasons best explained here. TL;DR: solutions based on Math.random() do not provide good uniqueness guarantees.

https://stackoverflow.com/questions/105034/how-do-i-create-a-guid-uuid/2117523#2117523

### To Reproduce

https://github.com/openai/openai-node/blob/master/src/core.ts#L1003-L1009

### Code snippets

```JavaScript
https://github.com/openai/openai-node/blob/master/src/core.ts#L1003-L1009
```

### OS

library code

### Node version

any

### Library version

4.6.0

**Comment by rattrayalex** [comment]
Thanks for reporting this. We are aware of this issue; strong uniqueness is not required for the use-cases where we apply the `uuid`s in this library. 

At time of implementation, the `crypto` module was not available in all JS runtimes that we target, which is why we chose `Math.random()`, despite it being a bit of a smell. However, this may have changed since, so it may be worth looking into whether we can upgrade.
