### ISSUE TITLE
code writing

### ISSUE THREAD

**Issue by ralyodio** [openai/openai-node#32]
### Describe the bug

I don't get back all the code from the api.

`write me a function in javascript that makes 10 parallel fetch requests simultaneously for 100 iterations`

the code is cut off.

### To Reproduce

```
const { Configuration, OpenAIApi } = require("openai");

const argv = require('minimist')(process.argv.slice(2));
console.log(argv.help);
const configuration = new Configuration({
  apiKey: 'xxx',
});
const openai = new OpenAIApi(configuration);

(async () => {

  const response = await openai.createCompletion({
    model: "code-davinci-002",
    prompt: `/* javascript: ${argv.help}  */`,
    temperature: 0,
    max_tokens: 256,
    top_p: 1,
    frequency_penalty: 0,
    presence_penalty: 0,
  });

  response.data.choices.map(c => console.log(c.text));
})();
```

`$ node code.js --help "write me a function that makes 10 parallel fetch requests simultaneously for 100 iterations"`

### OS

Linux

### Node version

19

### Library version

3.0.1

**Comment by ralyodio** [comment]
If I increase the token count I get an api limit error. How is that supposed to be of any use to anyone? I have a paid account and it says "no usage" for daily limit.

**Comment by schnerd** [comment]
@ralyodio I believe this is an issue with the API itself, rather than this specific package.

As you identified, increasing `max_tokens` is the best way to get more output. Can you say more about the "api limit error" you are receiving?

The models can also sometimes predict the "end of text" token – a place where it thinks output should stop, even if it hasn't hit max_tokens or at stop sequence yet. In this case you can use [logit_bias](https://beta.openai.com/docs/api-reference/completions/create#completions/create-logit_bias) to prevent the endoftext token from being generated:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/875591/209448573-e555c935-b802-4f25-ba3a-f55cbfd3c2e4.png">
