### ISSUE TITLE
createCompletionFromModel is missing

### ISSUE THREAD

**Issue by jimburch** [openai/openai-node#33]
### Describe the bug

According to the [fine-tuning docs on OpenAi](https://beta.openai.com/docs/guides/fine-tuning/use-a-fine-tuned-model), there should be a `createCompletionFromModel` function in your API:

```js
const response = await openai.createCompletionFromModel({
  model: FINE_TUNED_MODEL
  prompt: YOUR_PROMPT,
});
```

There is even a [post in the forums](https://community.openai.com/t/nodejs-completion-with-fine-tuned-model/14779/4) that says it was included in versions 2.0.2:

![image](https://user-images.githubusercontent.com/49823725/205823612-4a2bff72-8d5b-4758-a80f-c39de1749ba0.png)

But I'm getting errors saying that it's not part of the import. Is that function deprecated? How do we create a completion using a fine-tuning model?

### To Reproduce

I forked and cloned the repo to search for `createCompletionFromModel` to make sure I wasn't missing something, but it came up empty.

### OS

mac)S

### Node version

Node 16

### Library version

latest

**Comment by schnerd** [comment]
The fine-tuning docs were unfortunately out of date and have since been updated – `createCompletionFromModel` was removed in V3, and you should now be able to call any model  – including fine-tuned models – using `createCompletion`.

I'll try to make the upgrade guide in README.md clearer about this!
