### ISSUE TITLE
Cannot find name `File`.

### ISSUE THREAD

**Issue by rjamesnw** [openai/openai-node#48]
### Describe the bug

Imported the `openai` module and I'm getting an error for an undefined type `File`.

![image](https://user-images.githubusercontent.com/2531435/212184126-49bef740-2c0f-4820-b9f9-e99ac04f5ae4.png)

![image](https://user-images.githubusercontent.com/2531435/212184207-89ec3db2-f489-4434-9f17-6bdfd3cfe7be.png)

### To Reproduce

1. Run `npm install openai`.
2. Create a new NodeJS server-side project.
![image](https://user-images.githubusercontent.com/2531435/212185080-4ec94ffa-4b47-4c5c-992a-773b92219a9c.png)

### OS

Windows 10

### Node version

v16.6.1

### Library version

v3.1.0

**Comment by ahmedalawady** [comment]
@rjamesnw I used version 3.0.0 instead of 3.1.0 and it is working now with me, It seems bug in the new version

**Comment by ahmedalawady** [comment]
@rjamesnw I think it's a Typescript version compatibility, I had the same problem but when I update the Typescript version everything is working fine. I faced the problem when I run the debugger because the VScode using my global Typescript that was set up on my machine so I ran ` npm install -g typescript` is working fine now

**Comment by rjamesnw** [comment]
Note, a workaround is to add `type File=any;` to the top of the `index.d.ts` file in the `dist` directory.

**Comment by TimJohns** [comment]
Since it looks like you're using Node, in lieu of the workaround, you may be able to use one of the Node runtime configurations from [tsconfig/bases](https://github.com/tsconfig/bases), by adding it to your `tsconfig.json` with "extends".

I ran into this same issue with undefined `File` type in my Node 16 project, and resolved it by adding `"extends": "@tsconfig/node16/tsconfig.json"` to my `tsconfig.json` (full contents of my current working `tsconfig.json` below, for reference)


```
{
  "compilerOptions": {
      "module": "commonjs",
      "lib": ["ES2018"],
      "esModuleInterop": true,
      "allowSyntheticDefaultImports": true,
      "target": "es6",
      "noImplicitAny": true,
      "moduleResolution": "node",
      "sourceMap": true,
      "outDir": "dist",
      "baseUrl": ".",
      "paths": {
          "*": [
              "node_modules/*",
              "src/types/*"
          ]
      }
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "src/public"
  ],
  "extends": "@tsconfig/node16/tsconfig.json"
}
```

**Comment by almerindo** [comment]
It works for me! Thanks!

**Comment by ivanglushko** [comment]
Ran into this aswell

**Comment by bryanhelmig** [comment]
Create a `global.d.ts` file in your project's root or type definition folder, then add the following code:

```typescript
declare global {
  type File = any;
}
export {};
```

This should fix the issue.

**Comment by rattrayalex** [comment]
This is fixed in our [upcoming v4](https://github.com/openai/openai-node/discussions/182), which includes conveniences for file uploads.

**Comment by khanakia** [comment]
Non it's not solved still getting error

```
/test/node_modules/openai/_shims/formdata.js:6
exports.File = File;
               ^
ReferenceError: File is not defined
    at Object.<anonymous> (/test/node_modules/openai/_shims/formdata.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/test/node_modules/openai/src/uploads.ts:66:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```
