### ISSUE TITLE
Add a way to avoid printing the finalContent when using runFunctions

### ISSUE THREAD

**Issue by adaboese** [openai/openai-node#555]
### Confirm this is a feature request for the Node library and not the underlying OpenAI API.

- [X] This is a feature request for the Node library

### Describe the feature or improvement you're requesting

I have a routine that prints alphabet A-Z.

One function prints one letter at a time.

The problem is that OpenAI SDK also outputs the entire alphabet _again_, at the end.

Is there a way that would force it to return early without bothering with producing the final output?

```ts
const runner = openai.beta.chat.completions.runFunctions({
  functions: [
    {
      description: 'Prints letter',
      name: 'print_letter',
      parameters: {
        type: 'object',
        properties: {
          letter: {
            type: 'string',
            description: 'Letter to print',
          },
        },
        function: ({letter}) => {
          console.log(letter);
          return {message: letter};
        },
      }
    }
  ],
  messages: [
    {
      content: 'Print letters A to Z',
      role: 'user',
    },
  ],
  model: 'gpt-4-1106-preview',
});

await runner.finalFunctionCall();

console.log(await runner.finalContent());
```

Here the last `console.log` will print something along the lines of:

```
The alphabet between A and F has been listed:\n\nA\nB\nC\nD\nE\nF
```

I tried tapping into `.on('finalFunctionCall', ...` event, but that happens after `finalContent()` already has a result.

I really just need some sort of event that fires before it starts generating the final output, so I could abort early.

The example uses alphabet listing, which is quick. But in real-world scenario, that final content function can a long time/many tokens to generate.

**Comment by rattrayalex** [comment]
Several possibilities:
1. You don't have to print `finalContent`?
2. You can call `runner.abort()` at any time
3. As mentioned in the docs, if you pass `function_call: {name: …}`, it returns immediately after calling that function (and only loops to auto-recover parsing errors). I'm not sure if that helps your use-case since I'm a little unclear on exactly what you want.

I hope this helps!

**Comment by adaboese** [comment]
@rattrayalex I think you are missing the point.

> You don't have to print finalContent?

I need to know when the completions are done.

Maybe if we use a concrete example, it will be easier to understand the requirement.

I am creating an article generator – https://aimd.app

Journey begins by creating an outline suggestion.

For every heading, I use function to output it. (This way I get real-time updates)

I need to know when the entire outline has been printed.

Currently, the only way of knowing that is by waiting for `runner.finalFunctionCall()`.

However, by the time `runner.finalFunctionCall()` completes `runner.finalContent()` is also available, that means that I am waiting extra time for result even though my functions are not going to be called anymore.

In a toy example, that's a few seconds, but in a real-world scenario that can be extra 20-30 seconds.

i.e. This is either a bug or a missing feature in openai SDK as there is no way to resolve `finalFunctionCall` _before_ OpenAI also outputs summary of all the actions it took.

**Comment by adaboese** [comment]
I should mention that I was able to "hack" this by asking AI to include `currentSection` `totalSections` parameters in every function call, and when `currentSection === totalSection`, just abort the request. But this is a hack. This should be a feature of the SDK itself.

**Comment by rattrayalex** [comment]
Ahhh, you want `finalFunctionCall` to resolve before the final chat completion is done – basically, as soon as the model responds with an `assistant` message. Is that right?

That makes sense to me. I'm not sure how trivial implementation will be.

**Comment by adaboese** [comment]
Correct. That would greatly reduce the final response time for use cases that do not require the final content, which I would imagine is many.

**Comment by rattrayalex** [comment]
Ah, sorry, I didn't understand that you actually don't want to hear the model's response if it's not going to be a function call. 

To me, this actually sounds better suited to an API feature; something like `tool_choice: {type: 'function', function: 'any'}` or something – such that the API returns with an empty response when it would ordinarily respond with text. 

In any case, we don't want `await finalFunctionCall()` to actually stop the model, which is what you're looking for.

For now, I think your best bet is to intentionally abort the flow as soon as you start to get text content from the model, eg;

```ts
runner.on('content', (_delta, _snapshot) => {
  runner.abort();
})
```
This way you should only "burn" about one token.

I'll pass this feature request along to the API team, but we don't track API feature requests in this repo, so I'm going to go ahead and close this issue, since I think this solution is about as optimal as you can get today.

**Comment by adaboese** [comment]
```
runner.on('content', () => {
  runner.abort();
})
```

This works!

Thank you

**Comment by adaboese** [comment]
@rattrayalex It looks like `content` only gets called with the full output.

(I have `stream: true`)

Is there another event I could tap into that is fired as soon as content starts streaming?

**Comment by adaboese** [comment]
For anyone else reading this, make sure that you have `stream: true`. Otherwise, `content` event won't fire until the entire content is buffered.
